repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.21.0
    hooks:
      - id: typos
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        exclude: migrations/migration.sql|migrations/run_once.sql
      - id: trailing-whitespace
        exclude: migrations/migration.sql|migrations/run_once.sql
      - id: check-json
      - id: check-toml
