baseURL = "https://tdonovic.github.io/"
title = "tdonovic"
theme ="hugo-theme-basic"
languageCode = "en-au"
googleAnalytics = "UA-XXXXXXXXX-X"
enableEmoji = true 
copyright = "© 2020 tomas donovic"
description = "discoveries along the way"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  # change this!
  twitter = "siegerts"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "post/"

[[params.menu]]
  name = "post series"
  url = "series/"


[[params.menu]]
  name = "about"
  url = "about/"

[[params.menu]]
  name = "thesis"
  url = "thesis/"

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    hl_Lines = ""
    lineNoStart = 0
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "pastie"
    tabWidth = 4
